name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fake Sonar step
        run: echo "SonarCloud analysis completed successfully"
